// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WasteToValue.Api.Infrastructure.Persistence;

#nullable disable

namespace WasteToValue.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260915163518_InitialIntegratedSchema")]
    partial class InitialIntegratedSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WasteToValue.Api.Modules.Collections.Entities.CollectionSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("capacity");

                    b.Property<Guid?>("CollectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("collector_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<int>("ReservedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reserved_count");

                    b.Property<string>("ServiceArea")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("service_area");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("AVAILABLE")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("VehicleClass")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("vehicle_class");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Status", "StartsAt", "EndsAt")
                        .HasDatabaseName("ix_collection_slots_availability");

                    b.ToTable("collection_slots", (string)null);
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Collections.Entities.HandoverProof", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("PickupEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("pickup_event_id");

                    b.Property<Guid>("PickupRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("pickup_request_id");

                    b.Property<string>("ProofType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("proof_type");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<string>("VerificationHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("verification_hash");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<Guid?>("VerifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by");

                    b.HasKey("Id");

                    b.HasIndex("PickupEventId");

                    b.HasIndex("PickupRequestId");

                    b.ToTable("handover_proofs", (string)null);
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Collections.Entities.PickupEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("EventAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("event_type");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PickupRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("pickup_request_id");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("PickupRequestId", "EventAt")
                        .HasDatabaseName("ix_pickup_events_request_time");

                    b.ToTable("pickup_events", (string)null);
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Collections.Entities.PickupPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CollectionSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_slot_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("LKR")
                        .HasColumnName("currency");

                    b.Property<decimal>("EstimatedCost")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("estimated_cost");

                    b.Property<string>("FeasibilityStatus")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("feasibility_status");

                    b.Property<string>("HandlingRequirements")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("handling_requirements")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<DateTimeOffset>("ProposedEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proposed_end");

                    b.Property<DateTimeOffset>("ProposedStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proposed_start");

                    b.Property<string>("TravelEstimate")
                        .HasColumnType("jsonb")
                        .HasColumnName("travel_estimate");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CollectionSlotId");

                    b.ToTable("pickup_plans", (string)null);
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Collections.Entities.PickupRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CollectionSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_slot_id");

                    b.Property<Guid?>("CollectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("collector_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("PickupAddressEncrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pickup_address_encrypted");

                    b.Property<Guid>("RecoveryProposalId")
                        .HasColumnType("uuid")
                        .HasColumnName("recovery_proposal_id");

                    b.Property<DateTimeOffset>("ScheduledEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_end");

                    b.Property<DateTimeOffset>("ScheduledStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_start");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("CONFIRMED")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("verification_code");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CollectionSlotId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("RecoveryProposalId")
                        .IsUnique();

                    b.HasIndex("OwnerId", "Status")
                        .HasDatabaseName("ix_pickup_requests_owner_status");

                    b.ToTable("pickup_requests", (string)null);
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Items.Entities.AssessmentClarification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssessmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("QuestionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("ItemId");

                    b.ToTable("AssessmentClarifications", (string)null);
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Items.Entities.AssessmentEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("PhotoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("PhotoId");

                    b.ToTable("AssessmentEvidences", (string)null);
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Items.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("LocationArea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Status");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Items.Entities.ItemAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConditionGrade")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConditionSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("MissingInformation")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("OwnerReportedFunctionality")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SuggestedCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<string>("VisibleObservations")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "Version")
                        .IsUnique();

                    b.ToTable("ItemAssessments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Assessment_Confidence", "\"Confidence\" >= 0 AND \"Confidence\" <= 1");
                        });
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Items.Entities.ItemConditionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuestionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ItemId", "QuestionCode")
                        .IsUnique();

                    b.ToTable("ItemConditionAnswers", (string)null);
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Items.Entities.ItemPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("PhotoOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ItemId", "PhotoOrder");

                    b.ToTable("ItemPhotos", (string)null);
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Partners.Entities.AcceptanceRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("MinimumCondition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("minimum_condition");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<string>("Restrictions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("restrictions");

                    b.Property<string>("RouteType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("route_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId", "CategoryId", "RouteType")
                        .IsUnique()
                        .HasDatabaseName("uq_acceptance_rule");

                    b.ToTable("acceptance_rules", (string)null);
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Partners.Entities.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Capacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("capacity");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PartnerType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("partner_type");

                    b.Property<string>("ServiceArea")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("service_area");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("verification_status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("partners", (string)null);
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Partners.Entities.PartnerMembership", b =>
                {
                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("MembershipRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Representative")
                        .HasColumnName("membership_role");

                    b.HasKey("PartnerId", "UserId");

                    b.ToTable("partner_memberships", (string)null);
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Partners.Entities.RecipientNeed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<int>("QuantityFulfilled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("quantity_fulfilled");

                    b.Property<int>("QuantityRequired")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_required");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Open")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId");

                    b.ToTable("recipient_needs", (string)null);
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Recovery.Entities.ProposalDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid>("DecidedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("decision");

                    b.Property<string>("DecisionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("decision_type");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<int>("ProposalRevision")
                        .HasColumnType("integer")
                        .HasColumnName("proposal_revision");

                    b.Property<Guid>("RecoveryProposalId")
                        .HasColumnType("uuid")
                        .HasColumnName("recovery_proposal_id");

                    b.HasKey("Id");

                    b.HasIndex("DecidedBy", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("RecoveryProposalId", "ProposalRevision", "DecidedBy", "DecisionType")
                        .IsUnique();

                    b.ToTable("proposal_decisions", null, t =>
                        {
                            t.HasCheckConstraint("ck_proposal_decisions_type", "proposal_revision > 0 AND decision_type = 'OWNER_DECISION'");

                            t.HasCheckConstraint("ck_proposaldecision_decision", "decision IN ('APPROVED','REJECTED','REVISION_REQUESTED')");
                        });
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Recovery.Entities.RecoveryCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<int>("AssessmentVersion")
                        .HasColumnType("integer")
                        .HasColumnName("assessment_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("character(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset?>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int>("ItemRevision")
                        .HasColumnType("integer")
                        .HasColumnName("item_revision");

                    b.Property<decimal?>("MaximumPickupCost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("maximum_pickup_cost");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("objective");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("PreferredRoutesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("preferred_routes");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique()
                        .HasDatabaseName("uq_recovery_cases_active_item")
                        .HasFilter("status NOT IN ('REJECTED','COMPLETED','FAILED','CANCELLED')");

                    b.HasIndex("OwnerId", "Status");

                    b.ToTable("recovery_cases", null, t =>
                        {
                            t.HasCheckConstraint("ck_recovery_cases_revisions", "revision > 0 AND item_revision > 0 AND assessment_version > 0");

                            t.HasCheckConstraint("ck_recovery_cases_version", "version > 0");

                            t.HasCheckConstraint("ck_recoverycase_currency", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_recoverycase_maximum_pickup_cost", "maximum_pickup_cost IS NULL OR maximum_pickup_cost >= 0");

                            t.HasCheckConstraint("ck_recoverycase_status", "status IN ('DRAFT','PLANNING','AWAITING_INPUTS','AWAITING_APPROVAL','APPROVED','REJECTED','REVISION_REQUESTED','COMPLETED','FAILED','CANCELLED')");
                        });
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Recovery.Entities.RecoveryOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<int>("AssessmentVersion")
                        .HasColumnType("integer")
                        .HasColumnName("assessment_version");

                    b.Property<int>("CaseRevision")
                        .HasColumnType("integer")
                        .HasColumnName("case_revision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("character(3)")
                        .HasColumnName("currency");

                    b.Property<decimal?>("EstimatedNetValue")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("estimated_net_value");

                    b.Property<decimal?>("EstimatedPickupCost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("estimated_pickup_cost");

                    b.Property<decimal?>("EstimatedRepairCost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("estimated_repair_cost");

                    b.Property<decimal?>("EstimatedShortfall")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("estimated_shortfall");

                    b.Property<decimal?>("EstimatedValueHigh")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("estimated_value_high");

                    b.Property<decimal?>("EstimatedValueLow")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("estimated_value_low");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence");

                    b.Property<string>("IntegrationSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("integration_snapshot");

                    b.Property<string>("NonFinancialBenefitsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("non_financial_benefits");

                    b.Property<Guid>("RecoveryCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("recovery_case_id");

                    b.Property<bool>("RequiresPartner")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_partner");

                    b.Property<bool>("RequiresPickup")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_pickup");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("route_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("RecoveryCaseId", "Status");

                    b.ToTable("recovery_options", null, t =>
                        {
                            t.HasCheckConstraint("ck_recovery_options_balance", "estimated_net_value = GREATEST(estimated_value_low - estimated_repair_cost - estimated_pickup_cost, 0) AND estimated_shortfall = GREATEST(estimated_repair_cost + estimated_pickup_cost - estimated_value_low, 0)");

                            t.HasCheckConstraint("ck_recovery_options_bounds", "estimated_value_low <= estimated_value_high");

                            t.HasCheckConstraint("ck_recovery_options_complete", "status NOT IN ('VALIDATED','SELECTED') OR (estimated_value_low IS NOT NULL AND estimated_value_high IS NOT NULL AND estimated_repair_cost IS NOT NULL AND estimated_pickup_cost IS NOT NULL AND estimated_net_value IS NOT NULL AND estimated_shortfall IS NOT NULL)");

                            t.HasCheckConstraint("ck_recovery_options_pickup", "NOT requires_pickup OR requires_partner");

                            t.HasCheckConstraint("ck_recovery_options_revisions", "case_revision > 0 AND assessment_version > 0");

                            t.HasCheckConstraint("ck_recovery_options_version", "version > 0");

                            t.HasCheckConstraint("ck_recoveryoption_currency", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_recoveryoption_estimated_net_value", "estimated_net_value IS NULL OR estimated_net_value >= 0");

                            t.HasCheckConstraint("ck_recoveryoption_estimated_pickup_cost", "estimated_pickup_cost IS NULL OR estimated_pickup_cost >= 0");

                            t.HasCheckConstraint("ck_recoveryoption_estimated_repair_cost", "estimated_repair_cost IS NULL OR estimated_repair_cost >= 0");

                            t.HasCheckConstraint("ck_recoveryoption_estimated_shortfall", "estimated_shortfall IS NULL OR estimated_shortfall >= 0");

                            t.HasCheckConstraint("ck_recoveryoption_estimated_value_high", "estimated_value_high IS NULL OR estimated_value_high >= 0");

                            t.HasCheckConstraint("ck_recoveryoption_estimated_value_low", "estimated_value_low IS NULL OR estimated_value_low >= 0");

                            t.HasCheckConstraint("ck_recoveryoption_route_type", "route_type IN ('REUSE','DONATE','REPAIR_THEN_REUSE','RESELL','RECYCLE')");

                            t.HasCheckConstraint("ck_recoveryoption_status", "status IN ('DRAFT','VALIDATED','SELECTED','STALE','REJECTED')");
                        });
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Recovery.Entities.RecoveryProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AgentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_run_id");

                    b.Property<int>("CaseRevision")
                        .HasColumnType("integer")
                        .HasColumnName("case_revision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EstimateSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("estimate_snapshot");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("explanation");

                    b.Property<string>("InputSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_snapshot");

                    b.Property<string>("MatchFreshnessToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("match_freshness_token");

                    b.Property<Guid?>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<int?>("MatchVersion")
                        .HasColumnType("integer")
                        .HasColumnName("match_version");

                    b.Property<int>("OptionVersion")
                        .HasColumnType("integer")
                        .HasColumnName("option_version");

                    b.Property<string>("PickupFreshnessToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pickup_freshness_token");

                    b.Property<Guid?>("PickupPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("pickup_plan_id");

                    b.Property<int?>("PickupPlanVersion")
                        .HasColumnType("integer")
                        .HasColumnName("pickup_plan_version");

                    b.Property<string>("RecommendationOrigin")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("recommendation_origin");

                    b.Property<Guid>("RecoveryCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("recovery_case_id");

                    b.Property<Guid>("RecoveryOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("recovery_option_id");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("RecoveryOptionId");

                    b.HasIndex("RecoveryCaseId", "Revision")
                        .IsUnique();

                    b.ToTable("recovery_proposals", null, t =>
                        {
                            t.HasCheckConstraint("ck_recovery_proposals_expiry", "expires_at > created_at");

                            t.HasCheckConstraint("ck_recovery_proposals_match", "(match_id IS NULL AND match_version IS NULL AND match_freshness_token IS NULL) OR (match_id IS NOT NULL AND match_version > 0 AND match_freshness_token IS NOT NULL)");

                            t.HasCheckConstraint("ck_recovery_proposals_origin", "(recommendation_origin = 'HUMAN' AND agent_run_id IS NULL) OR (recommendation_origin = 'AGENT' AND agent_run_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_recovery_proposals_pickup", "(pickup_plan_id IS NULL AND pickup_plan_version IS NULL AND pickup_freshness_token IS NULL) OR (pickup_plan_id IS NOT NULL AND pickup_plan_version > 0 AND pickup_freshness_token IS NOT NULL AND match_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_recovery_proposals_revisions", "revision > 0 AND case_revision > 0 AND option_version > 0");

                            t.HasCheckConstraint("ck_recovery_proposals_version", "version > 0");

                            t.HasCheckConstraint("ck_recoveryproposal_recommendation_origin", "recommendation_origin IN ('HUMAN','AGENT')");

                            t.HasCheckConstraint("ck_recoveryproposal_status", "status IN ('DRAFT','AWAITING_APPROVAL','APPROVED','REJECTED','REVISION_REQUESTED','EXPIRED','EXECUTED','STALE')");
                        });
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Recovery.Entities.ValueReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("condition_grade");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("character(3)")
                        .HasColumnName("currency");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("route_type");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_name");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("source_reference");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("ValueHigh")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("value_high");

                    b.Property<decimal>("ValueLow")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("value_low");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "Condition", "Route", "Currency", "ObservedAt");

                    b.ToTable("value_references", null, t =>
                        {
                            t.HasCheckConstraint("ck_value_references_bounds", "value_low <= value_high");

                            t.HasCheckConstraint("ck_value_references_version", "version > 0");

                            t.HasCheckConstraint("ck_valuereference_condition_grade", "condition_grade IN ('EXCELLENT','GOOD','FAIR','POOR','UNSAFE','UNKNOWN')");

                            t.HasCheckConstraint("ck_valuereference_currency", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_valuereference_route_type", "route_type IN ('REUSE','DONATE','REPAIR_THEN_REUSE','RESELL','RECYCLE')");

                            t.HasCheckConstraint("ck_valuereference_value_high", "value_high IS NULL OR value_high >= 0");

                            t.HasCheckConstraint("ck_valuereference_value_low", "value_low IS NULL OR value_low >= 0");
                        });
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Collections.Entities.HandoverProof", b =>
                {
                    b.HasOne("WasteToValue.Api.Modules.Collections.Entities.PickupEvent", "PickupEvent")
                        .WithMany()
                        .HasForeignKey("PickupEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WasteToValue.Api.Modules.Collections.Entities.PickupRequest", "PickupRequest")
                        .WithMany("HandoverProofs")
                        .HasForeignKey("PickupRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PickupEvent");

                    b.Navigation("PickupRequest");
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Collections.Entities.PickupEvent", b =>
                {
                    b.HasOne("WasteToValue.Api.Modules.Collections.Entities.PickupRequest", "PickupRequest")
                        .WithMany("Events")
                        .HasForeignKey("PickupRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PickupRequest");
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Collections.Entities.PickupPlan", b =>
                {
                    b.HasOne("WasteToValue.Api.Modules.Collections.Entities.CollectionSlot", "CollectionSlot")
                        .WithMany()
                        .HasForeignKey("CollectionSlotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CollectionSlot");
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Collections.Entities.PickupRequest", b =>
                {
                    b.HasOne("WasteToValue.Api.Modules.Collections.Entities.CollectionSlot", "CollectionSlot")
                        .WithMany()
                        .HasForeignKey("CollectionSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CollectionSlot");
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Items.Entities.AssessmentClarification", b =>
                {
                    b.HasOne("WasteToValue.Api.Modules.Items.Entities.ItemAssessment", "Assessment")
                        .WithMany("Clarifications")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WasteToValue.Api.Modules.Items.Entities.Item", "Item")
                        .WithMany("Clarifications")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Items.Entities.AssessmentEvidence", b =>
                {
                    b.HasOne("WasteToValue.Api.Modules.Items.Entities.ItemAssessment", "Assessment")
                        .WithMany("Evidences")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WasteToValue.Api.Modules.Items.Entities.ItemPhoto", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Assessment");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Items.Entities.ItemAssessment", b =>
                {
                    b.HasOne("WasteToValue.Api.Modules.Items.Entities.Item", "Item")
                        .WithMany("Assessments")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Items.Entities.ItemConditionAnswer", b =>
                {
                    b.HasOne("WasteToValue.Api.Modules.Items.Entities.Item", "Item")
                        .WithMany("ConditionAnswers")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Items.Entities.ItemPhoto", b =>
                {
                    b.HasOne("WasteToValue.Api.Modules.Items.Entities.Item", "Item")
                        .WithMany("Photos")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Partners.Entities.AcceptanceRule", b =>
                {
                    b.HasOne("WasteToValue.Api.Modules.Partners.Entities.Partner", "Partner")
                        .WithMany("AcceptanceRules")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Partners.Entities.PartnerMembership", b =>
                {
                    b.HasOne("WasteToValue.Api.Modules.Partners.Entities.Partner", "Partner")
                        .WithMany("Memberships")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Partners.Entities.RecipientNeed", b =>
                {
                    b.HasOne("WasteToValue.Api.Modules.Partners.Entities.Partner", "Partner")
                        .WithMany("RecipientNeeds")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Recovery.Entities.ProposalDecision", b =>
                {
                    b.HasOne("WasteToValue.Api.Modules.Recovery.Entities.RecoveryProposal", null)
                        .WithMany()
                        .HasForeignKey("RecoveryProposalId", "ProposalRevision")
                        .HasPrincipalKey("Id", "Revision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Recovery.Entities.RecoveryOption", b =>
                {
                    b.HasOne("WasteToValue.Api.Modules.Recovery.Entities.RecoveryCase", null)
                        .WithMany()
                        .HasForeignKey("RecoveryCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Recovery.Entities.RecoveryProposal", b =>
                {
                    b.HasOne("WasteToValue.Api.Modules.Recovery.Entities.RecoveryCase", null)
                        .WithMany()
                        .HasForeignKey("RecoveryCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WasteToValue.Api.Modules.Recovery.Entities.RecoveryOption", null)
                        .WithMany()
                        .HasForeignKey("RecoveryOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Collections.Entities.PickupRequest", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("HandoverProofs");
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Items.Entities.Item", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("Clarifications");

                    b.Navigation("ConditionAnswers");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Items.Entities.ItemAssessment", b =>
                {
                    b.Navigation("Clarifications");

                    b.Navigation("Evidences");
                });

            modelBuilder.Entity("WasteToValue.Api.Modules.Partners.Entities.Partner", b =>
                {
                    b.Navigation("AcceptanceRules");

                    b.Navigation("Memberships");

                    b.Navigation("RecipientNeeds");
                });
#pragma warning restore 612, 618
        }
    }
}
